### ISSUE TITLE
NO sirve alv

### ISSUE THREAD

**Issue by VCAngel** [manghidev/mp-checkout-pro#1]
```suggestion
borra todo alv no sirve puta basura
```

**Comment by montesp** [comment]
SI esa madre no jala, que la borren

**Comment by manghidev** [comment]
No quiero alv

**Comment by VCAngel** [comment]
<img src="https://media.tenor.com/MXpTxtjJQN0AAAAM/breakdance-cat-electronic-jazz.gif" />

**Comment by manghidev** [comment]
Cerrado por el administrador
